-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2004 Altera Corporation
-- Any  megafunction  design,  and related netlist (encrypted  or  decrypted),
-- support information,  device programming or simulation file,  and any other
-- associated  documentation or information  provided by  Altera  or a partner
-- under  Altera's   Megafunction   Partnership   Program  may  be  used  only
-- to program  PLD  devices (but not masked  PLD  devices) from  Altera.   Any
-- other  use  of such  megafunction  design,  netlist,  support  information,
-- device programming or simulation file,  or any other  related documentation
-- or information  is prohibited  for  any  other purpose,  including, but not
-- limited to  modification,  reverse engineering,  de-compiling, or use  with
-- any other  silicon devices,  unless such use is  explicitly  licensed under
-- a separate agreement with  Altera  or a megafunction partner.  Title to the
-- intellectual property,  including patents,  copyrights,  trademarks,  trade
-- secrets,  or maskworks,  embodied in any such megafunction design, netlist,
-- support  information,  device programming or simulation file,  or any other
-- related documentation or information provided by  Altera  or a megafunction
-- partner, remains with Altera, the megafunction partner, or their respective
-- licensors. No other licenses, including any licenses needed under any third
-- party's intellectual property, are provided herein.


-- Generated by Quartus II Version 4.2 (Build Build 157 12/07/2004)
-- Created on Fri Mar 18 13:38:13 2005

-- Seven Segment Decoder
-- Written by Walter Lindermeir

--         a
--       f   b 
--         g
--       e   c
--         d

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Digitaltechnik 2
--  (c) 2007 R.Keller, W.Lindermeir, W.Zimmermann
--  Hochschule Esslingen
--  Letzte Aenderung: W. Lindermeir, 11/07


ENTITY Seven_seg_dec IS
PORT
(
state : IN STD_LOGIC_VECTOR(3 downto 0);
seven_segs : OUT STD_LOGIC_VECTOR(6 downto 0)
);
END Seven_seg_dec;

ARCHITECTURE Seven_seg_dec_architecture OF Seven_seg_dec IS
signal result    : std_logic_vector(6 downto 0);
BEGIN
comb: process (state)
begin
  case state is
  ---abcdefg
  when "0000" => result <= "1111110"; --0
  when "0001" => result <= "0110000"; --1
  when "0010" => result <= "1101101"; --2
  when "0011" => result <= "1111001"; --3
  when "0100" => result <= "0110011"; --4
  when "0101" => result <= "1011011"; --5
  when "0110" => result <= "1011111"; --6
  when "0111" => result <= "1110000"; --7
  when "1000" => result <= "1111111"; --8
  when "1001" => result <= "1110011"; --9
  when "1010" => result <= "1110111"; --A"-------";-- 
  when "1011" => result <= "0011111"; --b"-------";-- 
  when "1100" => result <= "1001110"; --C"-------";-- 
  when "1101" => result <= "0111101"; --d"-------";-- 
  when "1110" => result <= "1001111"; --E"-------";-- 
  when "1111" => result <= "1000111"; --F"-------";-- 
  when others => result <= "-------"; 
  end case;
end process; --comb

seven_segs <= NOT result;

END Seven_seg_dec_architecture;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

--  Digitaltechnik 2
--  (c) 2007 R.Keller, W.Lindermeir, W.Zimmermann
--  Hochschule Esslingen
--  Letzte Aenderung: W. Lindermeir, 11/07


--  Entity Declaration
ENTITY Dual_Seven_seg_dec IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		index_in_stim_file : IN STD_LOGIC_VECTOR(7 downto 0);
		seven_segs : OUT STD_LOGIC_VECTOR(13 downto 0)
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END Dual_Seven_seg_dec;

--  Architecture Body
ARCHITECTURE Dual_Seven_seg_dec_architecture OF Dual_Seven_seg_dec IS

	
BEGIN

dec_lsb: entity work.Seven_seg_dec
         port map(state => index_in_stim_file(3 downto 0), seven_segs => seven_segs(6 downto 0));

dec_msb: entity work.Seven_seg_dec
         port map(state => index_in_stim_file(7 downto 4), seven_segs => seven_segs(13 downto 7));


END Dual_Seven_seg_dec_architecture;
