-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2004 Altera Corporation
-- Any  megafunction  design,  and related netlist (encrypted  or  decrypted),
-- support information,  device programming or simulation file,  and any other
-- associated  documentation or information  provided by  Altera  or a partner
-- under  Altera's   Megafunction   Partnership   Program  may  be  used  only
-- to program  PLD  devices (but not masked  PLD  devices) from  Altera.   Any
-- other  use  of such  megafunction  design,  netlist,  support  information,
-- device programming or simulation file,  or any other  related documentation
-- or information  is prohibited  for  any  other purpose,  including, but not
-- limited to  modification,  reverse engineering,  de-compiling, or use  with
-- any other  silicon devices,  unless such use is  explicitly  licensed under
-- a separate agreement with  Altera  or a megafunction partner.  Title to the
-- intellectual property,  including patents,  copyrights,  trademarks,  trade
-- secrets,  or maskworks,  embodied in any such megafunction design, netlist,
-- support  information,  device programming or simulation file,  or any other
-- related documentation or information provided by  Altera  or a megafunction
-- partner, remains with Altera, the megafunction partner, or their respective
-- licensors. No other licenses, including any licenses needed under any third
-- party's intellectual property, are provided herein.


-- Generated by Quartus II Version 4.2 (Build Build 157 12/07/2004)
-- Created on Wed Feb 16 21:27:53 2005

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

--  Entity Declaration

--  Digitaltechnik 2
--  (c) 2007 R.Keller, W.Lindermeir, W.Zimmermann
--  Hochschule Esslingen
--  Letzte Aenderung: W. Lindermeir, 11/07


ENTITY stimulus_gen IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		clk : IN STD_LOGIC;
		reset_n : IN STD_LOGIC;
		next_stim_n : IN STD_LOGIC;
		prev_stim_n : IN STD_LOGIC;
		ALU_exp_result : OUT STD_LOGIC_VECTOR(7 downto 0);
		ALU_in1 : OUT STD_LOGIC_VECTOR(7 downto 0);
		ALU_in2 : OUT STD_LOGIC_VECTOR(7 downto 0);
		ALU_func : OUT STD_LOGIC_VECTOR(3 downto 0);
		ALU_c_in : OUT STD_LOGIC;
		ALU_exp_cozn : OUT STD_LOGIC_VECTOR(3 downto 0);
		index_in_stim_file : OUT STD_LOGIC_VECTOR(7 downto 0)
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END stimulus_gen;


--  Architecture Body

ARCHITECTURE stimulus_gen_architecture OF stimulus_gen IS

type stimulus_type is record
        ALU_exp_res_s : STD_LOGIC_VECTOR(7 downto 0);
        ALU_exp_s_s   : STD_LOGIC_VECTOR(3 downto 0);
		ALU_in1_s     : STD_LOGIC_VECTOR(7 downto 0);
		ALU_in2_s     : STD_LOGIC_VECTOR(7 downto 0);
		ALU_c_in_s    : STD_Logic;
		ALU_func_s    : STD_LOGIC_VECTOR(3 downto 0);
end record stimulus_type;

type stimulus_feld_type is array (natural range <>) of stimulus_type;
		
constant stimulus_feld : stimulus_feld_type := (
  16#000# => (ALU_func_s => X"8", ALU_in1_s => X"48", ALU_in2_s => X"01", ALU_c_in_s => '0', ALU_exp_res_s => X"90", ALU_exp_s_s => "0101"), -- alu_sll
  16#001# => (ALU_func_s => X"8", ALU_in1_s => X"F3", ALU_in2_s => X"6F", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#002# => (ALU_func_s => X"8", ALU_in1_s => X"9B", ALU_in2_s => X"94", ALU_c_in_s => '1', ALU_exp_res_s => X"B0", ALU_exp_s_s => "1101"), -- alu_sll
  16#003# => (ALU_func_s => X"8", ALU_in1_s => X"11", ALU_in2_s => X"04", ALU_c_in_s => '0', ALU_exp_res_s => X"10", ALU_exp_s_s => "1100"), -- alu_sll
  16#004# => (ALU_func_s => X"8", ALU_in1_s => X"C8", ALU_in2_s => X"12", ALU_c_in_s => '0', ALU_exp_res_s => X"20", ALU_exp_s_s => "1100"), -- alu_sll
  16#005# => (ALU_func_s => X"8", ALU_in1_s => X"5B", ALU_in2_s => X"56", ALU_c_in_s => '0', ALU_exp_res_s => X"C0", ALU_exp_s_s => "1101"), -- alu_sll
  16#006# => (ALU_func_s => X"8", ALU_in1_s => X"CE", ALU_in2_s => X"A2", ALU_c_in_s => '0', ALU_exp_res_s => X"38", ALU_exp_s_s => "1100"), -- alu_sll
  16#007# => (ALU_func_s => X"8", ALU_in1_s => X"C5", ALU_in2_s => X"F7", ALU_c_in_s => '0', ALU_exp_res_s => X"80", ALU_exp_s_s => "1101"), -- alu_sll
  16#008# => (ALU_func_s => X"8", ALU_in1_s => X"2A", ALU_in2_s => X"B1", ALU_c_in_s => '0', ALU_exp_res_s => X"54", ALU_exp_s_s => "0000"), -- alu_sll
  16#009# => (ALU_func_s => X"8", ALU_in1_s => X"CB", ALU_in2_s => X"7A", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#00A# => (ALU_func_s => X"8", ALU_in1_s => X"AB", ALU_in2_s => X"05", ALU_c_in_s => '0', ALU_exp_res_s => X"60", ALU_exp_s_s => "1100"), -- alu_sll
  16#00B# => (ALU_func_s => X"8", ALU_in1_s => X"52", ALU_in2_s => X"9E", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#00C# => (ALU_func_s => X"8", ALU_in1_s => X"11", ALU_in2_s => X"A5", ALU_c_in_s => '1', ALU_exp_res_s => X"20", ALU_exp_s_s => "1100"), -- alu_sll
  16#00D# => (ALU_func_s => X"8", ALU_in1_s => X"74", ALU_in2_s => X"F6", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#00E# => (ALU_func_s => X"8", ALU_in1_s => X"AF", ALU_in2_s => X"92", ALU_c_in_s => '1', ALU_exp_res_s => X"BC", ALU_exp_s_s => "1101"), -- alu_sll
  16#00F# => (ALU_func_s => X"8", ALU_in1_s => X"70", ALU_in2_s => X"EB", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#010# => (ALU_func_s => X"8", ALU_in1_s => X"07", ALU_in2_s => X"0D", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#011# => (ALU_func_s => X"8", ALU_in1_s => X"11", ALU_in2_s => X"EF", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#012# => (ALU_func_s => X"8", ALU_in1_s => X"08", ALU_in2_s => X"14", ALU_c_in_s => '0', ALU_exp_res_s => X"80", ALU_exp_s_s => "0101"), -- alu_sll
  16#013# => (ALU_func_s => X"8", ALU_in1_s => X"E8", ALU_in2_s => X"01", ALU_c_in_s => '0', ALU_exp_res_s => X"D0", ALU_exp_s_s => "1001"), -- alu_sll
  16#014# => (ALU_func_s => X"8", ALU_in1_s => X"32", ALU_in2_s => X"2C", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#015# => (ALU_func_s => X"8", ALU_in1_s => X"91", ALU_in2_s => X"53", ALU_c_in_s => '0', ALU_exp_res_s => X"88", ALU_exp_s_s => "1101"), -- alu_sll
  16#016# => (ALU_func_s => X"8", ALU_in1_s => X"50", ALU_in2_s => X"F9", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#017# => (ALU_func_s => X"8", ALU_in1_s => X"20", ALU_in2_s => X"70", ALU_c_in_s => '0', ALU_exp_res_s => X"20", ALU_exp_s_s => "0000"), -- alu_sll
  16#018# => (ALU_func_s => X"8", ALU_in1_s => X"FB", ALU_in2_s => X"2E", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#019# => (ALU_func_s => X"8", ALU_in1_s => X"69", ALU_in2_s => X"C5", ALU_c_in_s => '1', ALU_exp_res_s => X"20", ALU_exp_s_s => "1100"), -- alu_sll
  16#01A# => (ALU_func_s => X"8", ALU_in1_s => X"32", ALU_in2_s => X"67", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#01B# => (ALU_func_s => X"8", ALU_in1_s => X"AB", ALU_in2_s => X"73", ALU_c_in_s => '0', ALU_exp_res_s => X"58", ALU_exp_s_s => "1100"), -- alu_sll
  16#01C# => (ALU_func_s => X"8", ALU_in1_s => X"DA", ALU_in2_s => X"EB", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#01D# => (ALU_func_s => X"8", ALU_in1_s => X"7D", ALU_in2_s => X"5E", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#01E# => (ALU_func_s => X"8", ALU_in1_s => X"B3", ALU_in2_s => X"18", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#01F# => (ALU_func_s => X"8", ALU_in1_s => X"65", ALU_in2_s => X"05", ALU_c_in_s => '1', ALU_exp_res_s => X"A0", ALU_exp_s_s => "1101"), -- alu_sll
  16#020# => (ALU_func_s => X"8", ALU_in1_s => X"B0", ALU_in2_s => X"2C", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#021# => (ALU_func_s => X"8", ALU_in1_s => X"EA", ALU_in2_s => X"57", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#022# => (ALU_func_s => X"8", ALU_in1_s => X"44", ALU_in2_s => X"66", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#023# => (ALU_func_s => X"8", ALU_in1_s => X"02", ALU_in2_s => X"DF", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#024# => (ALU_func_s => X"8", ALU_in1_s => X"53", ALU_in2_s => X"05", ALU_c_in_s => '0', ALU_exp_res_s => X"60", ALU_exp_s_s => "1100"), -- alu_sll
  16#025# => (ALU_func_s => X"8", ALU_in1_s => X"27", ALU_in2_s => X"BD", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#026# => (ALU_func_s => X"8", ALU_in1_s => X"D4", ALU_in2_s => X"77", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#027# => (ALU_func_s => X"8", ALU_in1_s => X"30", ALU_in2_s => X"C7", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#028# => (ALU_func_s => X"8", ALU_in1_s => X"50", ALU_in2_s => X"42", ALU_c_in_s => '1', ALU_exp_res_s => X"40", ALU_exp_s_s => "1100"), -- alu_sll
  16#029# => (ALU_func_s => X"8", ALU_in1_s => X"39", ALU_in2_s => X"B5", ALU_c_in_s => '1', ALU_exp_res_s => X"20", ALU_exp_s_s => "1100"), -- alu_sll
  16#02A# => (ALU_func_s => X"8", ALU_in1_s => X"7B", ALU_in2_s => X"6D", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#02B# => (ALU_func_s => X"8", ALU_in1_s => X"A1", ALU_in2_s => X"BA", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#02C# => (ALU_func_s => X"8", ALU_in1_s => X"FA", ALU_in2_s => X"FE", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#02D# => (ALU_func_s => X"8", ALU_in1_s => X"FE", ALU_in2_s => X"08", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#02E# => (ALU_func_s => X"8", ALU_in1_s => X"8D", ALU_in2_s => X"02", ALU_c_in_s => '1', ALU_exp_res_s => X"34", ALU_exp_s_s => "1100"), -- alu_sll
  16#02F# => (ALU_func_s => X"8", ALU_in1_s => X"A0", ALU_in2_s => X"D0", ALU_c_in_s => '0', ALU_exp_res_s => X"A0", ALU_exp_s_s => "0001"), -- alu_sll
  16#030# => (ALU_func_s => X"8", ALU_in1_s => X"39", ALU_in2_s => X"D8", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#031# => (ALU_func_s => X"8", ALU_in1_s => X"BF", ALU_in2_s => X"E8", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#032# => (ALU_func_s => X"8", ALU_in1_s => X"19", ALU_in2_s => X"00", ALU_c_in_s => '1', ALU_exp_res_s => X"19", ALU_exp_s_s => "0000"), -- alu_sll
  16#033# => (ALU_func_s => X"8", ALU_in1_s => X"09", ALU_in2_s => X"F8", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#034# => (ALU_func_s => X"8", ALU_in1_s => X"CD", ALU_in2_s => X"69", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#035# => (ALU_func_s => X"8", ALU_in1_s => X"9A", ALU_in2_s => X"34", ALU_c_in_s => '1', ALU_exp_res_s => X"A0", ALU_exp_s_s => "1101"), -- alu_sll
  16#036# => (ALU_func_s => X"8", ALU_in1_s => X"25", ALU_in2_s => X"6F", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#037# => (ALU_func_s => X"8", ALU_in1_s => X"C9", ALU_in2_s => X"DF", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#038# => (ALU_func_s => X"8", ALU_in1_s => X"EF", ALU_in2_s => X"EA", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#039# => (ALU_func_s => X"8", ALU_in1_s => X"69", ALU_in2_s => X"A7", ALU_c_in_s => '0', ALU_exp_res_s => X"80", ALU_exp_s_s => "1101"), -- alu_sll
  16#03A# => (ALU_func_s => X"8", ALU_in1_s => X"3A", ALU_in2_s => X"7E", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#03B# => (ALU_func_s => X"8", ALU_in1_s => X"36", ALU_in2_s => X"94", ALU_c_in_s => '0', ALU_exp_res_s => X"60", ALU_exp_s_s => "1100"), -- alu_sll
  16#03C# => (ALU_func_s => X"8", ALU_in1_s => X"71", ALU_in2_s => X"2C", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#03D# => (ALU_func_s => X"8", ALU_in1_s => X"3B", ALU_in2_s => X"B2", ALU_c_in_s => '0', ALU_exp_res_s => X"EC", ALU_exp_s_s => "0101"), -- alu_sll
  16#03E# => (ALU_func_s => X"8", ALU_in1_s => X"FE", ALU_in2_s => X"63", ALU_c_in_s => '1', ALU_exp_res_s => X"F0", ALU_exp_s_s => "1001"), -- alu_sll
  16#03F# => (ALU_func_s => X"8", ALU_in1_s => X"ED", ALU_in2_s => X"DA", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#040# => (ALU_func_s => X"8", ALU_in1_s => X"E1", ALU_in2_s => X"4F", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#041# => (ALU_func_s => X"8", ALU_in1_s => X"86", ALU_in2_s => X"FD", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#042# => (ALU_func_s => X"8", ALU_in1_s => X"FF", ALU_in2_s => X"D7", ALU_c_in_s => '1', ALU_exp_res_s => X"80", ALU_exp_s_s => "1001"), -- alu_sll
  16#043# => (ALU_func_s => X"8", ALU_in1_s => X"01", ALU_in2_s => X"20", ALU_c_in_s => '1', ALU_exp_res_s => X"01", ALU_exp_s_s => "0000"), -- alu_sll
  16#044# => (ALU_func_s => X"8", ALU_in1_s => X"44", ALU_in2_s => X"E7", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#045# => (ALU_func_s => X"8", ALU_in1_s => X"A2", ALU_in2_s => X"BC", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#046# => (ALU_func_s => X"8", ALU_in1_s => X"E7", ALU_in2_s => X"D6", ALU_c_in_s => '1', ALU_exp_res_s => X"C0", ALU_exp_s_s => "1101"), -- alu_sll
  16#047# => (ALU_func_s => X"8", ALU_in1_s => X"AA", ALU_in2_s => X"9A", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#048# => (ALU_func_s => X"8", ALU_in1_s => X"68", ALU_in2_s => X"66", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#049# => (ALU_func_s => X"8", ALU_in1_s => X"38", ALU_in2_s => X"61", ALU_c_in_s => '0', ALU_exp_res_s => X"70", ALU_exp_s_s => "0000"), -- alu_sll
  16#04A# => (ALU_func_s => X"8", ALU_in1_s => X"AE", ALU_in2_s => X"C4", ALU_c_in_s => '0', ALU_exp_res_s => X"E0", ALU_exp_s_s => "1101"), -- alu_sll
  16#04B# => (ALU_func_s => X"8", ALU_in1_s => X"BD", ALU_in2_s => X"F2", ALU_c_in_s => '1', ALU_exp_res_s => X"F4", ALU_exp_s_s => "1101"), -- alu_sll
  16#04C# => (ALU_func_s => X"8", ALU_in1_s => X"F0", ALU_in2_s => X"07", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#04D# => (ALU_func_s => X"8", ALU_in1_s => X"B7", ALU_in2_s => X"55", ALU_c_in_s => '0', ALU_exp_res_s => X"E0", ALU_exp_s_s => "1101"), -- alu_sll
  16#04E# => (ALU_func_s => X"8", ALU_in1_s => X"9E", ALU_in2_s => X"39", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#04F# => (ALU_func_s => X"8", ALU_in1_s => X"9F", ALU_in2_s => X"8C", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#050# => (ALU_func_s => X"8", ALU_in1_s => X"8E", ALU_in2_s => X"9D", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#051# => (ALU_func_s => X"8", ALU_in1_s => X"F7", ALU_in2_s => X"BD", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#052# => (ALU_func_s => X"8", ALU_in1_s => X"28", ALU_in2_s => X"F8", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#053# => (ALU_func_s => X"8", ALU_in1_s => X"82", ALU_in2_s => X"58", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#054# => (ALU_func_s => X"8", ALU_in1_s => X"0A", ALU_in2_s => X"E8", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#055# => (ALU_func_s => X"8", ALU_in1_s => X"90", ALU_in2_s => X"7B", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#056# => (ALU_func_s => X"8", ALU_in1_s => X"E7", ALU_in2_s => X"E2", ALU_c_in_s => '0', ALU_exp_res_s => X"9C", ALU_exp_s_s => "1001"), -- alu_sll
  16#057# => (ALU_func_s => X"8", ALU_in1_s => X"07", ALU_in2_s => X"A1", ALU_c_in_s => '0', ALU_exp_res_s => X"0E", ALU_exp_s_s => "0000"), -- alu_sll
  16#058# => (ALU_func_s => X"8", ALU_in1_s => X"1B", ALU_in2_s => X"62", ALU_c_in_s => '1', ALU_exp_res_s => X"6C", ALU_exp_s_s => "0000"), -- alu_sll
  16#059# => (ALU_func_s => X"8", ALU_in1_s => X"AC", ALU_in2_s => X"E8", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#05A# => (ALU_func_s => X"8", ALU_in1_s => X"4E", ALU_in2_s => X"E2", ALU_c_in_s => '0', ALU_exp_res_s => X"38", ALU_exp_s_s => "1100"), -- alu_sll
  16#05B# => (ALU_func_s => X"8", ALU_in1_s => X"B3", ALU_in2_s => X"65", ALU_c_in_s => '0', ALU_exp_res_s => X"60", ALU_exp_s_s => "1100"), -- alu_sll
  16#05C# => (ALU_func_s => X"8", ALU_in1_s => X"28", ALU_in2_s => X"A8", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#05D# => (ALU_func_s => X"8", ALU_in1_s => X"3D", ALU_in2_s => X"05", ALU_c_in_s => '0', ALU_exp_res_s => X"A0", ALU_exp_s_s => "1101"), -- alu_sll
  16#05E# => (ALU_func_s => X"8", ALU_in1_s => X"D7", ALU_in2_s => X"30", ALU_c_in_s => '0', ALU_exp_res_s => X"D7", ALU_exp_s_s => "0001"), -- alu_sll
  16#05F# => (ALU_func_s => X"8", ALU_in1_s => X"C1", ALU_in2_s => X"12", ALU_c_in_s => '0', ALU_exp_res_s => X"04", ALU_exp_s_s => "1100"), -- alu_sll
  16#060# => (ALU_func_s => X"8", ALU_in1_s => X"68", ALU_in2_s => X"EB", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#061# => (ALU_func_s => X"8", ALU_in1_s => X"E2", ALU_in2_s => X"0F", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#062# => (ALU_func_s => X"8", ALU_in1_s => X"C5", ALU_in2_s => X"5B", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#063# => (ALU_func_s => X"8", ALU_in1_s => X"36", ALU_in2_s => X"C9", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#064# => (ALU_func_s => X"8", ALU_in1_s => X"10", ALU_in2_s => X"10", ALU_c_in_s => '1', ALU_exp_res_s => X"10", ALU_exp_s_s => "0000"), -- alu_sll
  16#065# => (ALU_func_s => X"8", ALU_in1_s => X"F6", ALU_in2_s => X"BB", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#066# => (ALU_func_s => X"8", ALU_in1_s => X"B8", ALU_in2_s => X"F7", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#067# => (ALU_func_s => X"8", ALU_in1_s => X"58", ALU_in2_s => X"71", ALU_c_in_s => '1', ALU_exp_res_s => X"B0", ALU_exp_s_s => "0101"), -- alu_sll
  16#068# => (ALU_func_s => X"8", ALU_in1_s => X"75", ALU_in2_s => X"68", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#069# => (ALU_func_s => X"8", ALU_in1_s => X"85", ALU_in2_s => X"90", ALU_c_in_s => '0', ALU_exp_res_s => X"85", ALU_exp_s_s => "0001"), -- alu_sll
  16#06A# => (ALU_func_s => X"8", ALU_in1_s => X"A8", ALU_in2_s => X"EA", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#06B# => (ALU_func_s => X"8", ALU_in1_s => X"DF", ALU_in2_s => X"3F", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#06C# => (ALU_func_s => X"8", ALU_in1_s => X"58", ALU_in2_s => X"28", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#06D# => (ALU_func_s => X"8", ALU_in1_s => X"1D", ALU_in2_s => X"14", ALU_c_in_s => '1', ALU_exp_res_s => X"D0", ALU_exp_s_s => "1101"), -- alu_sll
  16#06E# => (ALU_func_s => X"8", ALU_in1_s => X"1A", ALU_in2_s => X"AC", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#06F# => (ALU_func_s => X"8", ALU_in1_s => X"7A", ALU_in2_s => X"8B", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#070# => (ALU_func_s => X"8", ALU_in1_s => X"C1", ALU_in2_s => X"10", ALU_c_in_s => '1', ALU_exp_res_s => X"C1", ALU_exp_s_s => "0001"), -- alu_sll
  16#071# => (ALU_func_s => X"8", ALU_in1_s => X"C3", ALU_in2_s => X"C9", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#072# => (ALU_func_s => X"8", ALU_in1_s => X"90", ALU_in2_s => X"F9", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#073# => (ALU_func_s => X"8", ALU_in1_s => X"94", ALU_in2_s => X"04", ALU_c_in_s => '1', ALU_exp_res_s => X"40", ALU_exp_s_s => "1100"), -- alu_sll
  16#074# => (ALU_func_s => X"8", ALU_in1_s => X"18", ALU_in2_s => X"E0", ALU_c_in_s => '0', ALU_exp_res_s => X"18", ALU_exp_s_s => "0000"), -- alu_sll
  16#075# => (ALU_func_s => X"8", ALU_in1_s => X"88", ALU_in2_s => X"2F", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#076# => (ALU_func_s => X"8", ALU_in1_s => X"87", ALU_in2_s => X"CC", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#077# => (ALU_func_s => X"8", ALU_in1_s => X"62", ALU_in2_s => X"A1", ALU_c_in_s => '1', ALU_exp_res_s => X"C4", ALU_exp_s_s => "0101"), -- alu_sll
  16#078# => (ALU_func_s => X"8", ALU_in1_s => X"6F", ALU_in2_s => X"8F", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#079# => (ALU_func_s => X"8", ALU_in1_s => X"71", ALU_in2_s => X"50", ALU_c_in_s => '1', ALU_exp_res_s => X"71", ALU_exp_s_s => "0000"), -- alu_sll
  16#07A# => (ALU_func_s => X"8", ALU_in1_s => X"91", ALU_in2_s => X"94", ALU_c_in_s => '1', ALU_exp_res_s => X"10", ALU_exp_s_s => "1100"), -- alu_sll
  16#07B# => (ALU_func_s => X"8", ALU_in1_s => X"A5", ALU_in2_s => X"EA", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#07C# => (ALU_func_s => X"8", ALU_in1_s => X"1D", ALU_in2_s => X"63", ALU_c_in_s => '1', ALU_exp_res_s => X"E8", ALU_exp_s_s => "0101"), -- alu_sll
  16#07D# => (ALU_func_s => X"8", ALU_in1_s => X"B5", ALU_in2_s => X"76", ALU_c_in_s => '0', ALU_exp_res_s => X"40", ALU_exp_s_s => "1100"), -- alu_sll
  16#07E# => (ALU_func_s => X"8", ALU_in1_s => X"57", ALU_in2_s => X"0E", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#07F# => (ALU_func_s => X"8", ALU_in1_s => X"BD", ALU_in2_s => X"6B", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#080# => (ALU_func_s => X"8", ALU_in1_s => X"2A", ALU_in2_s => X"5B", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#081# => (ALU_func_s => X"8", ALU_in1_s => X"95", ALU_in2_s => X"26", ALU_c_in_s => '0', ALU_exp_res_s => X"40", ALU_exp_s_s => "1100"), -- alu_sll
  16#082# => (ALU_func_s => X"8", ALU_in1_s => X"8F", ALU_in2_s => X"26", ALU_c_in_s => '0', ALU_exp_res_s => X"C0", ALU_exp_s_s => "1101"), -- alu_sll
  16#083# => (ALU_func_s => X"8", ALU_in1_s => X"D9", ALU_in2_s => X"74", ALU_c_in_s => '0', ALU_exp_res_s => X"90", ALU_exp_s_s => "1101"), -- alu_sll
  16#084# => (ALU_func_s => X"8", ALU_in1_s => X"20", ALU_in2_s => X"8C", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#085# => (ALU_func_s => X"8", ALU_in1_s => X"3E", ALU_in2_s => X"75", ALU_c_in_s => '0', ALU_exp_res_s => X"C0", ALU_exp_s_s => "1101"), -- alu_sll
  16#086# => (ALU_func_s => X"8", ALU_in1_s => X"33", ALU_in2_s => X"CE", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#087# => (ALU_func_s => X"8", ALU_in1_s => X"7F", ALU_in2_s => X"70", ALU_c_in_s => '0', ALU_exp_res_s => X"7F", ALU_exp_s_s => "0000"), -- alu_sll
  16#088# => (ALU_func_s => X"8", ALU_in1_s => X"4E", ALU_in2_s => X"64", ALU_c_in_s => '0', ALU_exp_res_s => X"E0", ALU_exp_s_s => "1101"), -- alu_sll
  16#089# => (ALU_func_s => X"8", ALU_in1_s => X"7C", ALU_in2_s => X"53", ALU_c_in_s => '1', ALU_exp_res_s => X"E0", ALU_exp_s_s => "1101"), -- alu_sll
  16#08A# => (ALU_func_s => X"8", ALU_in1_s => X"85", ALU_in2_s => X"B4", ALU_c_in_s => '0', ALU_exp_res_s => X"50", ALU_exp_s_s => "1100"), -- alu_sll
  16#08B# => (ALU_func_s => X"8", ALU_in1_s => X"AB", ALU_in2_s => X"84", ALU_c_in_s => '1', ALU_exp_res_s => X"B0", ALU_exp_s_s => "1101"), -- alu_sll
  16#08C# => (ALU_func_s => X"8", ALU_in1_s => X"83", ALU_in2_s => X"F3", ALU_c_in_s => '0', ALU_exp_res_s => X"18", ALU_exp_s_s => "1100"), -- alu_sll
  16#08D# => (ALU_func_s => X"8", ALU_in1_s => X"32", ALU_in2_s => X"62", ALU_c_in_s => '0', ALU_exp_res_s => X"C8", ALU_exp_s_s => "0101"), -- alu_sll
  16#08E# => (ALU_func_s => X"8", ALU_in1_s => X"B2", ALU_in2_s => X"3B", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#08F# => (ALU_func_s => X"8", ALU_in1_s => X"32", ALU_in2_s => X"2E", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#090# => (ALU_func_s => X"8", ALU_in1_s => X"D9", ALU_in2_s => X"A6", ALU_c_in_s => '0', ALU_exp_res_s => X"40", ALU_exp_s_s => "1100"), -- alu_sll
  16#091# => (ALU_func_s => X"8", ALU_in1_s => X"E5", ALU_in2_s => X"76", ALU_c_in_s => '0', ALU_exp_res_s => X"40", ALU_exp_s_s => "1100"), -- alu_sll
  16#092# => (ALU_func_s => X"8", ALU_in1_s => X"20", ALU_in2_s => X"23", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#093# => (ALU_func_s => X"8", ALU_in1_s => X"46", ALU_in2_s => X"1E", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#094# => (ALU_func_s => X"8", ALU_in1_s => X"14", ALU_in2_s => X"22", ALU_c_in_s => '1', ALU_exp_res_s => X"50", ALU_exp_s_s => "0000"), -- alu_sll
  16#095# => (ALU_func_s => X"8", ALU_in1_s => X"BA", ALU_in2_s => X"D6", ALU_c_in_s => '0', ALU_exp_res_s => X"80", ALU_exp_s_s => "1101"), -- alu_sll
  16#096# => (ALU_func_s => X"8", ALU_in1_s => X"A5", ALU_in2_s => X"C9", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#097# => (ALU_func_s => X"8", ALU_in1_s => X"31", ALU_in2_s => X"8F", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#098# => (ALU_func_s => X"8", ALU_in1_s => X"A1", ALU_in2_s => X"1E", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#099# => (ALU_func_s => X"8", ALU_in1_s => X"C6", ALU_in2_s => X"CA", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#09A# => (ALU_func_s => X"8", ALU_in1_s => X"52", ALU_in2_s => X"EF", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#09B# => (ALU_func_s => X"8", ALU_in1_s => X"AB", ALU_in2_s => X"B8", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#09C# => (ALU_func_s => X"8", ALU_in1_s => X"52", ALU_in2_s => X"6E", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#09D# => (ALU_func_s => X"8", ALU_in1_s => X"94", ALU_in2_s => X"34", ALU_c_in_s => '1', ALU_exp_res_s => X"40", ALU_exp_s_s => "1100"), -- alu_sll
  16#09E# => (ALU_func_s => X"8", ALU_in1_s => X"7F", ALU_in2_s => X"60", ALU_c_in_s => '1', ALU_exp_res_s => X"7F", ALU_exp_s_s => "0000"), -- alu_sll
  16#09F# => (ALU_func_s => X"8", ALU_in1_s => X"63", ALU_in2_s => X"3A", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0A0# => (ALU_func_s => X"8", ALU_in1_s => X"48", ALU_in2_s => X"A0", ALU_c_in_s => '1', ALU_exp_res_s => X"48", ALU_exp_s_s => "0000"), -- alu_sll
  16#0A1# => (ALU_func_s => X"8", ALU_in1_s => X"23", ALU_in2_s => X"13", ALU_c_in_s => '1', ALU_exp_res_s => X"18", ALU_exp_s_s => "1100"), -- alu_sll
  16#0A2# => (ALU_func_s => X"8", ALU_in1_s => X"3B", ALU_in2_s => X"F6", ALU_c_in_s => '1', ALU_exp_res_s => X"C0", ALU_exp_s_s => "1101"), -- alu_sll
  16#0A3# => (ALU_func_s => X"8", ALU_in1_s => X"98", ALU_in2_s => X"9B", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0A4# => (ALU_func_s => X"8", ALU_in1_s => X"BB", ALU_in2_s => X"E4", ALU_c_in_s => '0', ALU_exp_res_s => X"B0", ALU_exp_s_s => "1101"), -- alu_sll
  16#0A5# => (ALU_func_s => X"8", ALU_in1_s => X"E8", ALU_in2_s => X"48", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0A6# => (ALU_func_s => X"8", ALU_in1_s => X"67", ALU_in2_s => X"CF", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0A7# => (ALU_func_s => X"8", ALU_in1_s => X"E5", ALU_in2_s => X"28", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0A8# => (ALU_func_s => X"8", ALU_in1_s => X"82", ALU_in2_s => X"0B", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0A9# => (ALU_func_s => X"8", ALU_in1_s => X"78", ALU_in2_s => X"02", ALU_c_in_s => '0', ALU_exp_res_s => X"E0", ALU_exp_s_s => "1101"), -- alu_sll
  16#0AA# => (ALU_func_s => X"8", ALU_in1_s => X"00", ALU_in2_s => X"B3", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "0010"), -- alu_sll
  16#0AB# => (ALU_func_s => X"8", ALU_in1_s => X"96", ALU_in2_s => X"D9", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0AC# => (ALU_func_s => X"8", ALU_in1_s => X"9C", ALU_in2_s => X"E7", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0AD# => (ALU_func_s => X"8", ALU_in1_s => X"EE", ALU_in2_s => X"8E", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0AE# => (ALU_func_s => X"8", ALU_in1_s => X"72", ALU_in2_s => X"FC", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0AF# => (ALU_func_s => X"8", ALU_in1_s => X"27", ALU_in2_s => X"12", ALU_c_in_s => '1', ALU_exp_res_s => X"9C", ALU_exp_s_s => "0101"), -- alu_sll
  16#0B0# => (ALU_func_s => X"8", ALU_in1_s => X"12", ALU_in2_s => X"5F", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0B1# => (ALU_func_s => X"8", ALU_in1_s => X"3B", ALU_in2_s => X"8C", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0B2# => (ALU_func_s => X"8", ALU_in1_s => X"00", ALU_in2_s => X"83", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "0010"), -- alu_sll
  16#0B3# => (ALU_func_s => X"8", ALU_in1_s => X"C9", ALU_in2_s => X"50", ALU_c_in_s => '1', ALU_exp_res_s => X"C9", ALU_exp_s_s => "0001"), -- alu_sll
  16#0B4# => (ALU_func_s => X"8", ALU_in1_s => X"E8", ALU_in2_s => X"E5", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0B5# => (ALU_func_s => X"8", ALU_in1_s => X"E6", ALU_in2_s => X"B4", ALU_c_in_s => '0', ALU_exp_res_s => X"60", ALU_exp_s_s => "1100"), -- alu_sll
  16#0B6# => (ALU_func_s => X"8", ALU_in1_s => X"7A", ALU_in2_s => X"5B", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0B7# => (ALU_func_s => X"8", ALU_in1_s => X"05", ALU_in2_s => X"2C", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0B8# => (ALU_func_s => X"8", ALU_in1_s => X"15", ALU_in2_s => X"3A", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0B9# => (ALU_func_s => X"8", ALU_in1_s => X"F2", ALU_in2_s => X"AF", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0BA# => (ALU_func_s => X"8", ALU_in1_s => X"F5", ALU_in2_s => X"6B", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0BB# => (ALU_func_s => X"8", ALU_in1_s => X"EA", ALU_in2_s => X"3D", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0BC# => (ALU_func_s => X"8", ALU_in1_s => X"91", ALU_in2_s => X"AC", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0BD# => (ALU_func_s => X"8", ALU_in1_s => X"ED", ALU_in2_s => X"BF", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0BE# => (ALU_func_s => X"8", ALU_in1_s => X"20", ALU_in2_s => X"22", ALU_c_in_s => '1', ALU_exp_res_s => X"80", ALU_exp_s_s => "0101"), -- alu_sll
  16#0BF# => (ALU_func_s => X"8", ALU_in1_s => X"4C", ALU_in2_s => X"B7", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0C0# => (ALU_func_s => X"8", ALU_in1_s => X"10", ALU_in2_s => X"2A", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0C1# => (ALU_func_s => X"8", ALU_in1_s => X"60", ALU_in2_s => X"23", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0C2# => (ALU_func_s => X"8", ALU_in1_s => X"76", ALU_in2_s => X"DD", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0C3# => (ALU_func_s => X"8", ALU_in1_s => X"03", ALU_in2_s => X"E7", ALU_c_in_s => '1', ALU_exp_res_s => X"80", ALU_exp_s_s => "1101"), -- alu_sll
  16#0C4# => (ALU_func_s => X"8", ALU_in1_s => X"EA", ALU_in2_s => X"E9", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0C5# => (ALU_func_s => X"8", ALU_in1_s => X"21", ALU_in2_s => X"74", ALU_c_in_s => '0', ALU_exp_res_s => X"10", ALU_exp_s_s => "1100"), -- alu_sll
  16#0C6# => (ALU_func_s => X"8", ALU_in1_s => X"70", ALU_in2_s => X"BC", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0C7# => (ALU_func_s => X"8", ALU_in1_s => X"3E", ALU_in2_s => X"DB", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0C8# => (ALU_func_s => X"8", ALU_in1_s => X"44", ALU_in2_s => X"6E", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0C9# => (ALU_func_s => X"8", ALU_in1_s => X"42", ALU_in2_s => X"85", ALU_c_in_s => '0', ALU_exp_res_s => X"40", ALU_exp_s_s => "1100"), -- alu_sll
  16#0CA# => (ALU_func_s => X"8", ALU_in1_s => X"5E", ALU_in2_s => X"F9", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0CB# => (ALU_func_s => X"8", ALU_in1_s => X"50", ALU_in2_s => X"D3", ALU_c_in_s => '0', ALU_exp_res_s => X"80", ALU_exp_s_s => "1101"), -- alu_sll
  16#0CC# => (ALU_func_s => X"8", ALU_in1_s => X"8B", ALU_in2_s => X"40", ALU_c_in_s => '1', ALU_exp_res_s => X"8B", ALU_exp_s_s => "0001"), -- alu_sll
  16#0CD# => (ALU_func_s => X"8", ALU_in1_s => X"9B", ALU_in2_s => X"60", ALU_c_in_s => '0', ALU_exp_res_s => X"9B", ALU_exp_s_s => "0001"), -- alu_sll
  16#0CE# => (ALU_func_s => X"8", ALU_in1_s => X"AC", ALU_in2_s => X"02", ALU_c_in_s => '0', ALU_exp_res_s => X"B0", ALU_exp_s_s => "1101"), -- alu_sll
  16#0CF# => (ALU_func_s => X"8", ALU_in1_s => X"82", ALU_in2_s => X"59", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0D0# => (ALU_func_s => X"8", ALU_in1_s => X"C0", ALU_in2_s => X"8C", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0D1# => (ALU_func_s => X"8", ALU_in1_s => X"28", ALU_in2_s => X"72", ALU_c_in_s => '1', ALU_exp_res_s => X"A0", ALU_exp_s_s => "0101"), -- alu_sll
  16#0D2# => (ALU_func_s => X"8", ALU_in1_s => X"9A", ALU_in2_s => X"DE", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0D3# => (ALU_func_s => X"8", ALU_in1_s => X"E3", ALU_in2_s => X"0E", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0D4# => (ALU_func_s => X"8", ALU_in1_s => X"39", ALU_in2_s => X"85", ALU_c_in_s => '0', ALU_exp_res_s => X"20", ALU_exp_s_s => "1100"), -- alu_sll
  16#0D5# => (ALU_func_s => X"8", ALU_in1_s => X"BF", ALU_in2_s => X"1A", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0D6# => (ALU_func_s => X"8", ALU_in1_s => X"BE", ALU_in2_s => X"B4", ALU_c_in_s => '0', ALU_exp_res_s => X"E0", ALU_exp_s_s => "1101"), -- alu_sll
  16#0D7# => (ALU_func_s => X"8", ALU_in1_s => X"0F", ALU_in2_s => X"8E", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0D8# => (ALU_func_s => X"8", ALU_in1_s => X"C4", ALU_in2_s => X"4D", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0D9# => (ALU_func_s => X"8", ALU_in1_s => X"D8", ALU_in2_s => X"09", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0DA# => (ALU_func_s => X"8", ALU_in1_s => X"D9", ALU_in2_s => X"69", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0DB# => (ALU_func_s => X"8", ALU_in1_s => X"75", ALU_in2_s => X"05", ALU_c_in_s => '1', ALU_exp_res_s => X"A0", ALU_exp_s_s => "1101"), -- alu_sll
  16#0DC# => (ALU_func_s => X"8", ALU_in1_s => X"5B", ALU_in2_s => X"9E", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0DD# => (ALU_func_s => X"8", ALU_in1_s => X"60", ALU_in2_s => X"37", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0DE# => (ALU_func_s => X"8", ALU_in1_s => X"C7", ALU_in2_s => X"AF", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0DF# => (ALU_func_s => X"8", ALU_in1_s => X"89", ALU_in2_s => X"40", ALU_c_in_s => '0', ALU_exp_res_s => X"89", ALU_exp_s_s => "0001"), -- alu_sll
  16#0E0# => (ALU_func_s => X"8", ALU_in1_s => X"DC", ALU_in2_s => X"9D", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0E1# => (ALU_func_s => X"8", ALU_in1_s => X"D8", ALU_in2_s => X"69", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0E2# => (ALU_func_s => X"8", ALU_in1_s => X"A2", ALU_in2_s => X"03", ALU_c_in_s => '1', ALU_exp_res_s => X"10", ALU_exp_s_s => "1100"), -- alu_sll
  16#0E3# => (ALU_func_s => X"8", ALU_in1_s => X"EF", ALU_in2_s => X"6E", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0E4# => (ALU_func_s => X"8", ALU_in1_s => X"66", ALU_in2_s => X"7A", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0E5# => (ALU_func_s => X"8", ALU_in1_s => X"3C", ALU_in2_s => X"6C", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0E6# => (ALU_func_s => X"8", ALU_in1_s => X"5B", ALU_in2_s => X"67", ALU_c_in_s => '0', ALU_exp_res_s => X"80", ALU_exp_s_s => "1101"), -- alu_sll
  16#0E7# => (ALU_func_s => X"8", ALU_in1_s => X"93", ALU_in2_s => X"C5", ALU_c_in_s => '1', ALU_exp_res_s => X"60", ALU_exp_s_s => "1100"), -- alu_sll
  16#0E8# => (ALU_func_s => X"8", ALU_in1_s => X"4F", ALU_in2_s => X"C7", ALU_c_in_s => '1', ALU_exp_res_s => X"80", ALU_exp_s_s => "1101"), -- alu_sll
  16#0E9# => (ALU_func_s => X"8", ALU_in1_s => X"76", ALU_in2_s => X"9D", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0EA# => (ALU_func_s => X"8", ALU_in1_s => X"55", ALU_in2_s => X"E8", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0EB# => (ALU_func_s => X"8", ALU_in1_s => X"27", ALU_in2_s => X"C9", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0EC# => (ALU_func_s => X"8", ALU_in1_s => X"DE", ALU_in2_s => X"B5", ALU_c_in_s => '0', ALU_exp_res_s => X"C0", ALU_exp_s_s => "1101"), -- alu_sll
  16#0ED# => (ALU_func_s => X"8", ALU_in1_s => X"47", ALU_in2_s => X"5E", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0EE# => (ALU_func_s => X"8", ALU_in1_s => X"E0", ALU_in2_s => X"24", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0EF# => (ALU_func_s => X"8", ALU_in1_s => X"98", ALU_in2_s => X"F4", ALU_c_in_s => '0', ALU_exp_res_s => X"80", ALU_exp_s_s => "1101"), -- alu_sll
  16#0F0# => (ALU_func_s => X"8", ALU_in1_s => X"3F", ALU_in2_s => X"95", ALU_c_in_s => '1', ALU_exp_res_s => X"E0", ALU_exp_s_s => "1101"), -- alu_sll
  16#0F1# => (ALU_func_s => X"8", ALU_in1_s => X"FC", ALU_in2_s => X"78", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0F2# => (ALU_func_s => X"8", ALU_in1_s => X"85", ALU_in2_s => X"77", ALU_c_in_s => '1', ALU_exp_res_s => X"80", ALU_exp_s_s => "1101"), -- alu_sll
  16#0F3# => (ALU_func_s => X"8", ALU_in1_s => X"54", ALU_in2_s => X"E6", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0F4# => (ALU_func_s => X"8", ALU_in1_s => X"4C", ALU_in2_s => X"54", ALU_c_in_s => '1', ALU_exp_res_s => X"C0", ALU_exp_s_s => "1101"), -- alu_sll
  16#0F5# => (ALU_func_s => X"8", ALU_in1_s => X"52", ALU_in2_s => X"AB", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0F6# => (ALU_func_s => X"8", ALU_in1_s => X"8F", ALU_in2_s => X"7B", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0F7# => (ALU_func_s => X"8", ALU_in1_s => X"8A", ALU_in2_s => X"6C", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0F8# => (ALU_func_s => X"8", ALU_in1_s => X"26", ALU_in2_s => X"CE", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0F9# => (ALU_func_s => X"8", ALU_in1_s => X"65", ALU_in2_s => X"DD", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0FA# => (ALU_func_s => X"8", ALU_in1_s => X"42", ALU_in2_s => X"FA", ALU_c_in_s => '0', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0FB# => (ALU_func_s => X"8", ALU_in1_s => X"B2", ALU_in2_s => X"05", ALU_c_in_s => '1', ALU_exp_res_s => X"40", ALU_exp_s_s => "1100"), -- alu_sll
  16#0FC# => (ALU_func_s => X"8", ALU_in1_s => X"C8", ALU_in2_s => X"28", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0FD# => (ALU_func_s => X"8", ALU_in1_s => X"81", ALU_in2_s => X"9F", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110"), -- alu_sll
  16#0FE# => (ALU_func_s => X"8", ALU_in1_s => X"A0", ALU_in2_s => X"8C", ALU_c_in_s => '1', ALU_exp_res_s => X"00", ALU_exp_s_s => "1110")  -- alu_sll
  );

signal i : natural;
	
BEGIN

assert stimulus_feld'high <= natural'high
   report "Error: Feld ist zu gross. Zaehler i vergroessern!"
   severity error;

seq: process( clk, reset_n ) is
begin
   if reset_n = '0' then
       -- reset condition
       i <= 0;
   elsif rising_edge(clk) then
      if next_stim_n = '0' then
         -- next stimuls index
         if i = stimulus_feld'high then
            i <= 0;
         else
            i <= i+1;
         end if;
      elsif prev_stim_n = '0' then
         -- previous stimulus index
         if i =  0 then
            i <= stimulus_feld'high;
         else
            i <= i-1;
         end if;
      end if;
      
   end if;
end process seq;


ALU_exp_result   <= stimulus_feld(i).ALU_exp_res_s;
ALU_exp_cozn     <= stimulus_feld(i).ALU_exp_s_s;
ALU_in1          <= stimulus_feld(i).ALU_in1_s;
ALU_in2          <= stimulus_feld(i).ALU_in2_s;
ALU_c_in         <= stimulus_feld(i).ALU_c_in_s;
ALU_func  <= stimulus_feld(i).ALU_func_s;

index_in_stim_file <= std_logic_vector(to_unsigned(i,8));

END stimulus_gen_architecture;
