-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2010 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 9.1 (Build Build 304 01/25/2010)
-- Created on Mon May 31 13:29:07 2010
--
-- Hochschule Esslingen, Fakultät IT
-- Copyright W. Zimmermann, W. Lindermeir, R. Keller   04/2010
-- Letzte Änderung: R. Keller  03/2019
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY NOT_V IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	GENERIC(TP_LH : INTEGER := 1;
			TP_HL : INTEGER := 1);
	PORT
	(
		IN1 : IN STD_LOGIC;
		OUTP : OUT STD_LOGIC
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END NOT_V;


--  Architecture Body

ARCHITECTURE NOT_V_architecture OF NOT_V IS
	
BEGIN
	NOT_Tp:  PROCESS (IN1)
	  variable OUTP_var: std_logic;
	BEGIN
	  OUTP_var := NOT(IN1);
	  IF (OUTP_var = '0') THEN
	    OUTP <= TRANSPORT OUTP_var after (TP_HL*1ns);
	  ELSE
	    OUTP <= TRANSPORT OUTP_var after (TP_LH*1ns);
	  END IF;
	END PROCESS NOT_Tp;

END NOT_V_architecture;
