-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions
-- and other software and tools, and its AMPP partner logic
-- functions, and any output files from any of the foregoing
-- (including device programming or simulation files), and any
-- associated documentation or information are expressly subject
-- to the terms and conditions of the Altera Program License
-- Subscription Agreement, Altera MegaCore Function License
-- Agreement, or other applicable license agreement, including,
-- without limitation, that your use is for the sole purpose of
-- programming logic devices manufactured by Altera and sold by
-- Altera or its authorized distributors.  Please refer to the
-- applicable agreement for further details.


-- Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
-- Created on Mon Apr 15 16:35:51 2019

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY vhdl_Decoder IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		x_0 : IN STD_LOGIC;
		x_1 : IN STD_LOGIC;
		x_2 : IN STD_LOGIC;
		x_3 : IN STD_LOGIC;
		a : OUT STD_LOGIC;
		b : OUT STD_LOGIC;
		c : OUT STD_LOGIC;
		d : OUT STD_LOGIC;
		e : OUT STD_LOGIC;
		f : OUT STD_LOGIC;
		g : OUT STD_LOGIC
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!

END vhdl_Decoder;


--  Architecture Body

ARCHITECTURE vhdl_Decoder_architecture OF vhdl_Decoder IS


SIGNAL x: std_logic_vector(3 DOWNTO 0);
SIGNAL y: std_logic_vector(6 DOWNTO 0);

BEGIN

x <= (x_3,x_2,x_1,x_0);
(a,b,c,d,e,f,g) <= not y;

FktTab: PROCESS(x)
BEGIN
	case x is
		when "0000" => y <= "1111110";
		when "0001" => y <= "0110000";
		when "0010" => y <= "1101101";
		when "0011" => y <= "1111001";
		when "0100" => y <= "0110011";
		when "0101" => y <= "1011011";
		when "0110" => y <= "1011111";
		when "0111" => y <= "1110000";
		when "1000" => y <= "1111111";
		when "1001" => y <= "1110011";
		--when "1010" => y <= "1110111";
		--when "1011" => y <= "0011111";
		--when "1100" => y <= "1001110";
		--when "1101" => y <= "0111101";
		--when "1110" => y <= "1001111";
		--when "1111" => y <= "1000111";
		when others => y <= "-------";
	end case;

END process FktTab;


END vhdl_Decoder_architecture;
